/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package urlgeneratorservice;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import urlgeneratorservice.utils.RestUrlResource;
import urlgeneratorservice.utils.UrlResourceMapper;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;

@RestController("/")
public class MainController {
    @Autowired
    private UrlResourceMapper urlResourceMapper;

    @GetMapping
    public String getGreeting() {
        return "Hello world.";
    }

    @GetMapping("/url/{hash}")
    public String getUrl(@PathVariable String hash) throws IOException {
        return urlResourceMapper.getResource(hash);
    }

    @PostMapping("/url")
    public String createUrl(@RequestBody RestUrlResource restUrlResource) throws IOException, NoSuchAlgorithmException {
        String resource = restUrlResource.getResource();
        String expiration = restUrlResource.getExpiration();
        return urlResourceMapper.createResource(resource, expiration);
    }


}
