/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package urlgeneratorservice;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import urlgeneratorservice.utils.UrlResourceMapper;

@RestController("/")
public class MainController {
    @Autowired
    private UrlResourceMapper urlResourceMapper;

    @GetMapping
    public String getGreeting() {
        return "Hello world.";
    }

    @GetMapping("/url/{hash}")
    public String getUrl(@PathVariable String hash) {
        return urlResourceMapper.getResource(hash);
    }


}
